import type { Metadata } from 'next';
import { Hachi_Maru_Pop } from 'next/font/google';
import './globals.css';

export const hachiMaruPop = Hachi_Maru_Pop({
  variable: '--font-noto-sans-jp',
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hachiMaruPop.variable} antialiased`}>
        <header className="border-b py-2">
          <h1 className="font-hachiMaru">ぽけぽけふれんず。</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
